import { AiEntityFilterRegistry } from '../ai-filter.types';

export const connectionsRegistry: AiEntityFilterRegistry = {
  entityType: 'connections',
  fields: {
    topology: {
      ai: 'topology',
      grid: 'topology',
      type: 'set',
      description: 'Connection topology.',
      values: ['server_to_server', 'multi_server'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    lifecycle: {
      ai: 'lifecycle',
      grid: 'lifecycle',
      type: 'set',
      description: 'Connection lifecycle.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    criticality: {
      ai: 'criticality',
      grid: 'criticality',
      type: 'set',
      description: 'Connection criticality (effective value: the highest of the linked interfaces when the risk is derived).',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    data_class: {
      ai: 'data_class',
      grid: 'data_class',
      type: 'set',
      description: 'Connection data class (effective value: the highest of the linked interfaces when the risk is derived).',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    contains_pii: {
      ai: 'contains_pii',
      grid: 'contains_pii',
      type: 'set',
      description: 'Whether the connection carries personal data (effective value: from the linked interfaces when the risk is derived).',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    risk_mode: {
      ai: 'risk_mode',
      grid: 'risk_mode',
      type: 'set',
      description: 'Connection risk mode.',
      values: ['manual', 'derived'],
      discoverable: true,
      sortable: false,
      groupable: true,
    },
  },
  sortFields: {
    label: 'name',
    connection_reference: 'connection_reference',
    name: 'name',
    topology: 'topology',
    lifecycle: 'lifecycle',
    criticality: 'criticality',
    data_class: 'data_class',
    contains_pii: 'contains_pii',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  // criticality, data_class and contains_pii are grouped and discovered on the effective values
  // (ConnectionsService.effectiveRiskByIds / listFilterValues), not on these stored columns.
  aggregate: {
    baseTable: 'connections',
    alias: 'cn',
    groupFields: {
      topology: { expression: 'cn.topology' },
      lifecycle: { expression: 'cn.lifecycle' },
      criticality: { expression: 'cn.criticality' },
      data_class: { expression: 'cn.data_class' },
      contains_pii: { expression: 'cn.contains_pii' },
      risk_mode: { expression: 'cn.risk_mode' },
    },
  },
};
