import { AiEntityFilterRegistry } from '../ai-filter.types';
import { budgetAmountFields, budgetAmountSortFields, budgetFteFields, budgetFteSortFields } from './budget-amount-fields';

export const spendItemsRegistry: AiEntityFilterRegistry = {
  entityType: 'spend_items',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Spend item lifecycle status.',
      values: ['enabled', 'disabled'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    currency: {
      ai: 'currency',
      grid: 'currency',
      type: 'set',
      description: 'Spend item currency.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    supplier: {
      ai: 'supplier',
      grid: 'supplier_name',
      type: 'set',
      description: 'Supplier name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    paying_company: {
      ai: 'paying_company',
      grid: 'paying_company_name',
      type: 'set',
      description: 'Paying company name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    account: {
      ai: 'account',
      grid: 'account_display',
      type: 'set',
      description: 'Account display value.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    owner_it: {
      ai: 'owner_it',
      grid: 'owner_it_name',
      type: 'set',
      description: 'IT owner display name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    owner_business: {
      ai: 'owner_business',
      grid: 'owner_business_name',
      type: 'set',
      description: 'Business owner display name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    analytics_category: {
      ai: 'analytics_category',
      grid: 'analytics_category_name',
      type: 'set',
      description: 'Value of the line on the default analytics dimension. Other dimensions, when the tenant has any, are the analytics:<code> fields.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    cost_center: {
      ai: 'cost_center',
      grid: 'cost_center_label',
      type: 'set',
      description: 'Cost center of the line, as "code · name".',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    cost_center_path: {
      ai: 'cost_center_path',
      grid: 'cost_center_path',
      type: 'text',
      description: 'Names of the cost center and of the groups above it, from the top group down, joined with " › ". Filter on a group name to get every line under that group.',
      sortable: true,
      groupable: true,
    },
    budget_holder: {
      ai: 'budget_holder',
      grid: 'budget_holder_name',
      type: 'set',
      description: 'Budget holder: the owner of the line\'s cost center, read from the cost center (not stored on the line). null is a line without a cost center or whose cost center has no budget holder.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    run_build: {
      ai: 'run_build',
      grid: 'run_build',
      type: 'set',
      description: 'Run (keeping existing services running) or build (new capabilities and projects). null is a line without the value.',
      values: ['run', 'build', null],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    allocation_method: {
      ai: 'allocation_method',
      grid: 'allocation_method_label',
      type: 'set',
      description: 'Allocation method label.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: false,
    },
    contract: {
      ai: 'contract',
      grid: 'contract_name',
      type: 'set',
      description: 'Latest linked contract name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: false,
    },
    project_name: {
      ai: 'project_name',
      grid: 'project_name',
      type: 'text',
      description: 'Names of the linked projects, comma separated. A filter keeps a line linked to any selected project; a line linked to several projects groups under the combination.',
      sortable: true,
      groupable: false,
    },
    project_stream: {
      ai: 'project_stream',
      grid: 'project_stream_name',
      type: 'set',
      description: 'Streams of the linked projects, comma separated. A filter keeps a line linked to any selected stream; a line linked to several streams groups under the combination.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    project_category: {
      ai: 'project_category',
      grid: 'project_category_name',
      type: 'set',
      description: 'Categories of the linked projects, comma separated. A filter keeps a line linked to any selected category; a line linked to several categories groups under the combination.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    effective_start: {
      ai: 'effective_start',
      grid: 'effective_start',
      type: 'date',
      description: 'Effective start date.',
      sortable: true,
      groupable: false,
    },
    end_of_validity: {
      ai: 'end_of_validity',
      grid: 'disabled_at',
      type: 'date',
      description: 'End of validity: the last day the item is in service. Blank means no end.',
      sortable: true,
      groupable: false,
    },
    effective_end: {
      ai: 'effective_end',
      grid: 'disabled_at',
      type: 'date',
      description: 'Deprecated alias of end_of_validity. Use end_of_validity.',
      sortable: true,
      groupable: false,
    },
    ...budgetAmountFields(),
    ...budgetFteFields(),
  },
  sortFields: {
    label: 'product_name',
    status: 'status',
    currency: 'currency',
    supplier: 'supplier_name',
    paying_company: 'paying_company_name',
    account: 'account_display',
    owner_it: 'owner_it_name',
    owner_business: 'owner_business_name',
    analytics_category: 'analytics_category_name',
    cost_center: 'cost_center_label',
    cost_center_path: 'cost_center_path',
    budget_holder: 'budget_holder_name',
    run_build: 'run_build',
    allocation_method: 'allocation_method_label',
    contract: 'contract_name',
    project_name: 'project_name',
    project_stream: 'project_stream_name',
    project_category: 'project_category_name',
    effective_start: 'effective_start',
    end_of_validity: 'disabled_at',
    effective_end: 'disabled_at',
    ...budgetAmountSortFields(),
    ...budgetFteSortFields(),
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'spend_items',
    alias: 'si',
    groupFields: {
      status: { expression: 'si.status' },
      currency: { expression: 'si.currency' },
      supplier: {
        expression: 'sup.name',
        joins: [
          `LEFT JOIN suppliers sup ON sup.id = si.supplier_id AND sup.tenant_id = si.tenant_id`,
        ],
      },
      paying_company: {
        expression: 'comp.name',
        joins: [
          `LEFT JOIN companies comp ON comp.id = si.paying_company_id AND comp.tenant_id = si.tenant_id`,
        ],
      },
      account: {
        expression: `NULLIF(TRIM(CONCAT_WS(' ', acc.account_number, acc.account_name)), '')`,
        joins: [
          `LEFT JOIN accounts acc ON acc.id = si.account_id AND acc.tenant_id = si.tenant_id`,
        ],
      },
      owner_it: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(u_it.first_name, ' ', u_it.last_name)), ''), u_it.email)`,
        joins: [
          `LEFT JOIN users u_it ON u_it.id = si.owner_it_id AND u_it.tenant_id = si.tenant_id`,
        ],
      },
      owner_business: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(u_biz.first_name, ' ', u_biz.last_name)), ''), u_biz.email)`,
        joins: [
          `LEFT JOIN users u_biz ON u_biz.id = si.owner_business_id AND u_biz.tenant_id = si.tenant_id`,
        ],
      },
      // The default dimension through its link (the legacy item column is no longer written).
      analytics_category: {
        expression: 'ac.name',
        joins: [
          `LEFT JOIN analytics_axes ax_def ON ax_def.tenant_id = si.tenant_id AND ax_def.is_default`,
          `LEFT JOIN spend_item_analytics_values av_def ON av_def.tenant_id = si.tenant_id AND av_def.item_id = si.id AND av_def.axis_id = ax_def.id`,
          `LEFT JOIN analytics_categories ac ON ac.id = av_def.category_id AND ac.tenant_id = av_def.tenant_id`,
        ],
      },
      cost_center: {
        expression: `CASE WHEN cc.id IS NULL THEN NULL ELSE CONCAT(cc.code, ' · ', cc.name) END`,
        joins: [
          `LEFT JOIN cost_centers cc ON cc.id = si.cost_center_id AND cc.tenant_id = si.tenant_id`,
        ],
      },
      budget_holder: {
        expression: `CASE WHEN u_bh.id IS NULL THEN NULL ELSE COALESCE(NULLIF(TRIM(CONCAT(u_bh.first_name, ' ', u_bh.last_name)), ''), u_bh.email) END`,
        joins: [
          `LEFT JOIN cost_centers cc_bh ON cc_bh.id = si.cost_center_id AND cc_bh.tenant_id = si.tenant_id`,
          `LEFT JOIN users u_bh ON u_bh.id = cc_bh.owner_user_id AND u_bh.tenant_id = cc_bh.tenant_id`,
        ],
      },
      run_build: { expression: 'si.run_build' },
    },
  },
};
